# -*- coding: utf-8 -*-
"""geoint.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YtbdIGv3i-0OrEs_xF0eHPGQY1jLUALK
"""

import sys
!{sys.executable} -m pip install pandas requests dash jupyter_dash

import pandas as pd
import requests
from jupyter_dash import JupyterDash
import dash.dcc as dcc
import dash.html as html
from dash.dependencies import Input, Output

print("Libraries installed and imported successfully!")
print("Next, we can start discussing the data acquisition strategy for each source.")

# To securely store your ACLED API key and email, you can use Colab's Secrets manager.
# Click on the '🔑' icon in the left panel, add a new secret named 'ACLED_API_KEY' and 'ACLED_EMAIL'.

import requests
import pandas as pd
from google.colab import userdata

def fetch_acled_data(api_key, email, region="South Asia", start_date=None, end_date=None, limit=1000):
    """Fetches conflict data from the ACLED API.

    Args:
        api_key (str): Your ACLED API key.
        email (str): Your ACLED account email.
        region (str, optional): The region to query. Defaults to "South Asia".
        start_date (str, optional): Start date in YYYY-MM-DD format. Defaults to None.
        end_date (str, optional): End date in YYYY-MM-DD format. Defaults to None.
        limit (int, optional): Number of records to fetch per request. Defaults to 1000.

    Returns:
        pd.DataFrame: A DataFrame containing the ACLED data.
    """
    base_url = "https://api.acleddata.com/acled/read"
    params = {
        "key": api_key,
        "email": email,
        "region": region,
        "limit": limit,
        "fields": "event_date|country|admin1|location|latitude|longitude|actor1|assoc_actor_1|interaction|event_type|fatalities"
    }

    if start_date:
        params["event_date"] = f">={start_date}"
    if end_date:
        params["event_date"] += f";<={end_date}" if start_date else f"<={end_date}"

    all_data = []
    page = 1
    while True:
        params["page"] = page
        try:
            response = requests.get(base_url, params=params)
            response.raise_for_status() # Raise an exception for HTTP errors
            data = response.json()

            if not data['data']:
                break # No more data

            all_data.extend(data['data'])

            # Check if there are more pages (ACLED API usually has a 'next_page_url' or similar in metadata)
            # For simplicity, we'll stop if a page returns less than the limit, assuming it's the last page.
            if len(data['data']) < limit:
                break
            page += 1

        except requests.exceptions.RequestException as e:
            print(f"Error fetching ACLED data: {e}")
            break

    return pd.DataFrame(all_data)

# Example Usage (uncomment to run after setting up secrets)
# ACLED_API_KEY = userdata.get('ACLED_API_KEY') # Retrieve from Colab secrets
# ACLED_EMAIL = userdata.get('ACLED_EMAIL')     # Retrieve from Colab secrets

# if ACLED_API_KEY and ACLED_EMAIL:
#     acled_df = fetch_acled_data(ACLED_API_KEY, ACLED_EMAIL, start_date="2023-01-01", end_date="2023-12-31", region="South Asia")
#     if not acled_df.empty:
#         print(f"Fetched {len(acled_df)} ACLED events.")
#         display(acled_df.head())
#     else:
#         print("No ACLED data fetched.")
# else:
#     print("Please set 'ACLED_API_KEY' and 'ACLED_EMAIL' in Colab secrets to fetch ACLED data.")

"""### 🔥 NASA FIRMS API Integration

The `fetch_nasa_firms` function was designed to fetch real-time fire and thermal anomaly data using the NASA FIRMS API. It constructs a URL with your API key, desired region (bounding box), and sensor type (VIIRS_SNPP_NRT in this case), then reads the CSV response directly into a pandas DataFrame.

Here's the function:

"""

import pandas as pd
import requests

def fetch_nasa_firms(api_key, bbox=[73.0, 27.0, 97.0, 37.0]):
    """Fetch Thermal Anomalies (Fires/Explosions) from NASA FIRMS.

    Args:
        api_key (str): Your NASA FIRMS Map Key.
        bbox (list): Bounding box [min_lon, min_lat, max_lon, max_lat].

    Returns:
        pd.DataFrame: DataFrame of FIRMS data, or empty DataFrame if error.
    """
    # Ensure bbox is a comma-separated string for the URL
    bbox_str = ",".join(map(str, bbox))
    url = f"https://firms.modaps.eosdis.nasa.gov/api/area/csv/{api_key}/VIIRS_SNPP_NRT/{bbox_str}/1"
    try:
        df = pd.read_csv(url)
        return df
    except requests.exceptions.RequestException as e:
        print(f"Error fetching NASA FIRMS data: {e}")
        return pd.DataFrame()
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        return pd.DataFrame()

# Example Usage (uncomment to run after setting up secrets)
# NASA_API_KEY = userdata.get('NASA_FIRMS_KEY') # Retrieve from Colab secrets

# if NASA_API_KEY:
#     firms_data = fetch_nasa_firms(NASA_API_KEY)
#     if not firms_data.empty:
#         print(f"Fetched {len(firms_data)} FIRMS records.")
#         display(firms_data.head())
#     else:
#         print("No NASA FIRMS data fetched.")
# else:
#     print("Please set 'NASA_FIRMS_KEY' in Colab secrets to fetch NASA FIRMS data.")

"""### Next Steps for Visualizing the Data (using Dash)

Since you've already imported `dash` and `jupyter_dash`, the next steps would be to set up a basic Dash application structure. Here's a general outline:

1.  **Initialize the Dash App**: Create an instance of `JupyterDash`.
2.  **Define the App Layout**: Use `dash.html` and `dash.dcc` components to structure your dashboard. This includes elements like titles, dropdowns, graphs, and maps.
3.  **Implement Callbacks**: Use `@app.callback` decorators to create interactive components. Callbacks will link user inputs (e.g., selecting a date range, clicking a button) to updates in the output (e.g., refreshing a graph, updating map layers).
4.  **Integrate Data Fetching**: Call your data acquisition functions (like `fetch_acled_data`, `fetch_nasa_firms`, `fetch_sentinel_imagery` etc.) within your app's logic, perhaps triggered by callbacks or loaded once at the start.
5.  **Run the App**: Launch the Dash app.

Here's a minimal example to get you started with a Dash application structure. You'll expand this with your specific data fetching and visualization components.

"""

from dash import Dash # Changed from jupyter_dash to dash
import dash.dcc as dcc
import dash.html as html
from dash.dependencies import Input, Output

# Assuming fetch_acled_data, fetch_nasa_firms and userdata are available from previous cells
from google.colab import userdata
import pandas as pd # Ensure pandas is imported for pd.to_datetime
import plotly.graph_objects as go # For plotly figures
import random

# 1. Initialize the Dash App
app = Dash(__name__) # Changed from JupyterDash to Dash

# 2. Define the App Layout
app.layout = html.Div([
    html.H1("Siya-Monitor Pro Dashboard"),
    html.Div(id='live-data-status', children='Loading data...'),
    dcc.Graph(id='acled-map', figure={}), # New graph for ACLED data
    dcc.Graph(id='example-graph'),
    html.Button('Refresh Data', id='refresh-button', n_clicks=0)
])

# 3. Implement Callbacks
@app.callback(
    Output('live-data-status', 'children'),
    Output('acled-map', 'figure'), # New output for ACLED map
    Output('example-graph', 'figure'),
    Input('refresh-button', 'n_clicks')
)
def update_dashboard(n_clicks):
    # Retrieve API keys from Colab secrets
    ACLED_API_KEY = userdata.get('ACLED_API_KEY')
    ACLED_EMAIL = userdata.get('ACLED_EMAIL')

    # --- ACLED Data Fetching and Visualization ---
    acled_fig = go.Figure() # Default empty figure
    acled_status_msg = "ACLED data not fetched. Please set ACLED API key and email in Colab secrets."

    if ACLED_API_KEY and ACLED_EMAIL:
        end_date = pd.to_datetime('today').strftime('%Y-%m-%d')
        start_date = (pd.to_datetime('today') - pd.DateOffset(days=30)).strftime('%Y-%m-%d')
        acled_df = fetch_acled_data(ACLED_API_KEY, ACLED_EMAIL, region="South Asia", start_date=start_date, end_date=end_date)

        if not acled_df.empty:
            acled_fig = go.Figure(go.Scattermapbox(
                lat=acled_df['latitude'],
                lon=acled_df['longitude'],
                mode='markers',
                marker=go.scattermapbox.Marker(
                    size=8,
                    color='red',
                    opacity=0.7
                ),
                text=acled_df['event_type'] + '<br>' + acled_df['location'] + ', ' + acled_df['country'],
                hoverinfo='text'
            ))
            acled_fig.update_layout(
                mapbox_style="open-street-map",
                mapbox_center_lat=acled_df['latitude'].mean(),
                mapbox_center_lon=acled_df['longitude'].mean(),
                mapbox_zoom=4,
                title="ACLED Conflict Events (Last 30 Days)",
                margin={"r":0,"t":40,"l":0,"b":0}
            )
            acled_status_msg = f"Fetched {len(acled_df)} ACLED events. "
        else:
            acled_status_msg = "No ACLED data found for the specified period."

    # --- Simulate fetching data for example graph ---
    example_fig = go.Figure(data=[go.Scatter(y=[random.randint(1, 10) for _ in range(10)])])
    example_fig.update_layout(title_text=f"Sample Data ({n_clicks} refreshes)")

    status_message = f"{acled_status_msg}Data last refreshed at: {pd.to_datetime('now').strftime('%Y-%m-%d %H:%M:%S')}"

    return status_message, acled_fig, example_fig

# 4. Run the App
# To run the app in Colab, you'll typically use mode='inline' or mode='external'
# Note: In Colab, you might need to use app.run(mode='inline') or similar depending on Dash version
app.run(port=8050)

print("Dash app structure defined. You can uncomment `app.run_server` to launch the dashboard.")

"""### Exploring NASA FIRMS Data

I will now call the `fetch_nasa_firms` function to retrieve the latest thermal anomaly data. Remember to set your `NASA_FIRMS_KEY` in Colab secrets for this to work.
"""

# Retrieve NASA API key from Colab secrets
NASA_API_KEY = userdata.get('NASA_FIRMS_KEY')

if NASA_API_KEY:
    print("Fetching NASA FIRMS data...")
    firms_data = fetch_nasa_firms(NASA_API_KEY)
    if not firms_data.empty:
        print(f"Fetched {len(firms_data)} FIRMS records.")
        display(firms_data.head())
    else:
        print("No NASA FIRMS data fetched or an error occurred.")
else:
    print("Please set 'NASA_FIRMS_KEY' in Colab secrets to fetch NASA FIRMS data.")