# -*- coding: utf-8 -*-
"""geoint.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YtbdIGv3i-0OrEs_xF0eHPGQY1jLUALK
"""

import sys
!{sys.executable} -m pip install pandas requests dash jupyter_dash

import pandas as pd
import requests
from jupyter_dash import JupyterDash
import dash.dcc as dcc
import dash.html as html
from dash.dependencies import Input, Output

print("Libraries installed and imported successfully!")
print("Next, we can start discussing the data acquisition strategy for each source.")

# To securely store your ACLED API key and email, you can use Colab's Secrets manager.
# Click on the '🔑' icon in the left panel, add a new secret named 'ACLED_API_KEY' and 'ACLED_EMAIL'.

import requests
import pandas as pd
from google.colab import userdata

def fetch_acled_data(api_key, email, region="South Asia", start_date=None, end_date=None, limit=1000):
    """Fetches conflict data from the ACLED API.

    Args:
        api_key (str): Your ACLED API key.
        email (str): Your ACLED account email.
        region (str, optional): The region to query. Defaults to "South Asia".
        start_date (str, optional): Start date in YYYY-MM-DD format. Defaults to None.
        end_date (str, optional): End date in YYYY-MM-DD format. Defaults to None.
        limit (int, optional): Number of records to fetch per request. Defaults to 1000.

    Returns:
        pd.DataFrame: A DataFrame containing the ACLED data.
    """
    base_url = "https://api.acleddata.com/acled/read"
    params = {
        "key": api_key,
        "email": email,
        "region": region,
        "limit": limit,
        "fields": "event_date|country|admin1|location|latitude|longitude|actor1|assoc_actor_1|interaction|event_type|fatalities"
    }

    if start_date:
        params["event_date"] = f">={start_date}"
    if end_date:
        params["event_date"] += f";<={end_date}" if start_date else f"<={end_date}"

    all_data = []
    page = 1
    while True:
        params["page"] = page
        try:
            response = requests.get(base_url, params=params)
            response.raise_for_status() # Raise an exception for HTTP errors
            data = response.json()

            if not data['data']:
                break # No more data

            all_data.extend(data['data'])

            # Check if there are more pages (ACLED API usually has a 'next_page_url' or similar in metadata)
            # For simplicity, we'll stop if a page returns less than the limit, assuming it's the last page.
            if len(data['data']) < limit:
                break
            page += 1

        except requests.exceptions.RequestException as e:
            print(f"Error fetching ACLED data: {e}")
            break

    return pd.DataFrame(all_data)

# Example Usage (uncomment to run after setting up secrets)
# ACLED_API_KEY = userdata.get('ACLED_API_KEY') # Retrieve from Colab secrets
# ACLED_EMAIL = userdata.get('ACLED_EMAIL')     # Retrieve from Colab secrets

# if ACLED_API_KEY and ACLED_EMAIL:
#     acled_df = fetch_acled_data(ACLED_API_KEY, ACLED_EMAIL, start_date="2023-01-01", end_date="2023-12-31", region="South Asia")
#     if not acled_df.empty:
#         print(f"Fetched {len(acled_df)} ACLED events.")
#         display(acled_df.head())
#     else:
#         print("No ACLED data fetched.")
# else:
#     print("Please set 'ACLED_API_KEY' and 'ACLED_EMAIL' in Colab secrets to fetch ACLED data.")

"""### 🔥 NASA FIRMS API Integration

The `fetch_nasa_firms` function was designed to fetch real-time fire and thermal anomaly data using the NASA FIRMS API. It constructs a URL with your API key, desired region (bounding box), and sensor type (VIIRS_SNPP_NRT in this case), then reads the CSV response directly into a pandas DataFrame.

Here's the function:

"""

import pandas as pd
import requests

def fetch_nasa_firms(api_key, bbox=[73.0, 27.0, 97.0, 37.0]):
    """Fetch Thermal Anomalies (Fires/Explosions) from NASA FIRMS.

    Args:
        api_key (str): Your NASA FIRMS Map Key.
        bbox (list): Bounding box [min_lon, min_lat, max_lon, max_lat].

    Returns:
        pd.DataFrame: DataFrame of FIRMS data, or empty DataFrame if error.
    """
    # Ensure bbox is a comma-separated string for the URL
    bbox_str = ",".join(map(str, bbox))
    url = f"https://firms.modaps.eosdis.nasa.gov/api/area/csv/{api_key}/VIIRS_SNPP_NRT/{bbox_str}/1"
    try:
        df = pd.read_csv(url)
        return df
    except requests.exceptions.RequestException as e:
        print(f"Error fetching NASA FIRMS data: {e}")
        return pd.DataFrame()
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        return pd.DataFrame()

# Example Usage (uncomment to run after setting up secrets)
# NASA_API_KEY = userdata.get('NASA_FIRMS_KEY') # Retrieve from Colab secrets

# if NASA_API_KEY:
#     firms_data = fetch_nasa_firms(NASA_API_KEY)
#     if not firms_data.empty:
#         print(f"Fetched {len(firms_data)} FIRMS records.")
#         display(firms_data.head())
#     else:
#         print("No NASA FIRMS data fetched.")
# else:
#     print("Please set 'NASA_FIRMS_KEY' in Colab secrets to fetch NASA FIRMS data.")

"""### Next Steps for Visualizing the Data (using Dash)

Since you've already imported `dash` and `jupyter_dash`, the next steps would be to set up a basic Dash application structure. Here's a general outline:

1.  **Initialize the Dash App**: Create an instance of `JupyterDash`.
2.  **Define the App Layout**: Use `dash.html` and `dash.dcc` components to structure your dashboard. This includes elements like titles, dropdowns, graphs, and maps.
3.  **Implement Callbacks**: Use `@app.callback` decorators to create interactive components. Callbacks will link user inputs (e.g., selecting a date range, clicking a button) to updates in the output (e.g., refreshing a graph, updating map layers).
4.  **Integrate Data Fetching**: Call your data acquisition functions (like `fetch_acled_data`, `fetch_nasa_firms`, `fetch_sentinel_imagery` etc.) within your app's logic, perhaps triggered by callbacks or loaded once at the start.
5.  **Run the App**: Launch the Dash app.

Here's a minimal example to get you started with a Dash application structure. You'll expand this with your specific data fetching and visualization components.

"""

from dash import Dash # Changed from jupyter_dash to dash
import dash.dcc as dcc
import dash.html as html
from dash.dependencies import Input, Output

# Assuming fetch_acled_data, fetch_nasa_firms and userdata are available from previous cells
from google.colab import userdata
import pandas as pd # Ensure pandas is imported for pd.to_datetime
import plotly.graph_objects as go # For plotly figures
import random

# 1. Initialize the Dash App
app = Dash(__name__) # Changed from JupyterDash to Dash

# 2. Define the App Layout
app.layout = html.Div([
    html.H1("Siya-Monitor Pro Dashboard"),
    html.Div(id='live-data-status', children='Loading data...'),
    dcc.Graph(id='acled-map', figure={}), # New graph for ACLED data
    dcc.Graph(id='example-graph'),
    html.Button('Refresh Data', id='refresh-button', n_clicks=0)
])

# 3. Implement Callbacks
@app.callback(
    Output('live-data-status', 'children'),
    Output('acled-map', 'figure'), # New output for ACLED map
    Output('example-graph', 'figure'),
    Input('refresh-button', 'n_clicks')
)
def update_dashboard(n_clicks):
    # Retrieve API keys from Colab secrets
    ACLED_API_KEY = userdata.get('ACLED_API_KEY')
    ACLED_EMAIL = userdata.get('ACLED_EMAIL')

    # --- ACLED Data Fetching and Visualization ---
    acled_fig = go.Figure() # Default empty figure
    acled_status_msg = "ACLED data not fetched. Please set ACLED API key and email in Colab secrets."

    if ACLED_API_KEY and ACLED_EMAIL:
        end_date = pd.to_datetime('today').strftime('%Y-%m-%d')
        start_date = (pd.to_datetime('today') - pd.DateOffset(days=30)).strftime('%Y-%m-%d')
        acled_df = fetch_acled_data(ACLED_API_KEY, ACLED_EMAIL, region="South Asia", start_date=start_date, end_date=end_date)

        if not acled_df.empty:
            acled_fig = go.Figure(go.Scattermapbox(
                lat=acled_df['latitude'],
                lon=acled_df['longitude'],
                mode='markers',
                marker=go.scattermapbox.Marker(
                    size=8,
                    color='red',
                    opacity=0.7
                ),
                text=acled_df['event_type'] + '<br>' + acled_df['location'] + ', ' + acled_df['country'],
                hoverinfo='text'
            ))
            acled_fig.update_layout(
                mapbox_style="open-street-map",
                mapbox_center_lat=acled_df['latitude'].mean(),
                mapbox_center_lon=acled_df['longitude'].mean(),
                mapbox_zoom=4,
                title="ACLED Conflict Events (Last 30 Days)",
                margin={"r":0,"t":40,"l":0,"b":0}
            )
            acled_status_msg = f"Fetched {len(acled_df)} ACLED events. "
        else:
            acled_status_msg = "No ACLED data found for the specified period."

    # --- Simulate fetching data for example graph ---
    example_fig = go.Figure(data=[go.Scatter(y=[random.randint(1, 10) for _ in range(10)])])
    example_fig.update_layout(title_text=f"Sample Data ({n_clicks} refreshes)")

    status_message = f"{acled_status_msg}Data last refreshed at: {pd.to_datetime('now').strftime('%Y-%m-%d %H:%M:%S')}"

    return status_message, acled_fig, example_fig

# 4. Run the App
# To run the app in Colab, you'll typically use mode='inline' or mode='external'
# Note: In Colab, you might need to use app.run(mode='inline') or similar depending on Dash version
app.run(port=8050)

print("Dash app structure defined. You can uncomment `app.run_server` to launch the dashboard.")

# we need to install some libraries as they are not default on the system
!pip install geodatasets cartopy

import geopandas
import matplotlib.pyplot as plt
from cartopy import crs as ccrs
from geodatasets import get_path


# let's get our basic earth data

path = get_path("naturalearth.land")
world = geopandas.read_file(path)

# and test our libraries loaded

world.plot()

crs = ccrs.epsg("3857")
world_epsg = world.to_crs(epsg="3857")

fig, axs = plt.subplots(1, 2, subplot_kw={"projection": crs}, figsize=(10, 5))
axs[0].set(title='EPSG:4326')
axs[1].set(title='EPSG:3857')
world.plot(ax=axs[0])
world_epsg.plot(ax=axs[1])
import pandas as pd
df = pd.read_csv('https://firms.modaps.eosdis.nasa.gov/content/notebooks/sample_viirs_snpp_071223.csv')

# show top 5 records
df.head()

# now convert latitude, longitude values into point geometry

gdf = geopandas.GeoDataFrame(
    df, geometry=geopandas.points_from_xy(df.longitude, df.latitude), crs="EPSG:4326"
)

# show top 3 records
gdf.head(3)
# optional: set outline and fill colors
ax = world.plot(color="lightgrey", edgecolor="black")

# We can now plot our ``GeoDataFrame``.
gdf.plot(ax=ax, color="red", markersize=0.1)

plt.show()


# create Canada subset

df_canada = df[(df['longitude'] >= -150) & (df['latitude'] >= 40) & (df['longitude'] <= -49) & (df['latitude'] <= 79)].copy()

# create geometry for points using latitude and longitude and specifying projection as EPSG:4326

gdf = geopandas.GeoDataFrame(
    df_canada, geometry=geopandas.points_from_xy(df_canada.longitude, df_canada.latitude), crs="EPSG:4326"
)

# set our extent
extent = [-150, 40, -49, 79]
ax = world.plot(figsize=(10, 10), color="grey", edgecolor="black")
ax.set_xlim([extent[0],  extent[2]])
ax.set_ylim([extent[1],  extent[3]])

ax.set(title='Canada wildfires July 12, 2023')

# We can now plot our ``GeoDataFrame``.
gdf.plot(ax=ax, color="red", markersize=1)

plt.show()


# convert aqc_date and aqc_time to acq_datetime as datetime object
df_canada['acq_datetime'] = pd.to_datetime(df_canada['acq_date'] + ' ' + df_canada['acq_time'].astype(str).str.zfill(4), format='%Y-%m-%d %H%M')
gdf = geopandas.GeoDataFrame(
    df_canada, geometry=geopandas.points_from_xy(df_canada.longitude, df_canada.latitude), crs="EPSG:4326"
)
# find maximum time from our dataset since we are pretending current date time is July 12 2023, 19:50(7:50pm) GMT.
# if the data were recent, we would set dt_max = pd.Timestamp.now();
dt_max = gdf['acq_datetime'].max()

# create our subsets for 4 color classes

# less than or equal to 1 hour; gdf1 <= 1hour
gdf1 = gdf[gdf['acq_datetime'] >= (dt_max - pd.Timedelta(hours=1))]

# greater than 1 hour but less than or equal to 4 hours; gdf2 > 1 hour and gdf2 <= 4 hours
gdf2 = gdf[(gdf['acq_datetime'] >= (dt_max - pd.Timedelta(hours=4))) & (gdf['acq_datetime'] < (dt_max - pd.Timedelta(hours=1)))]

# greater than 4 hours but less than or equal to 12 hours; gdf3 > 4 hours and gdf2 <= 12 hours
gdf3 = gdf[(gdf['acq_datetime'] >= (dt_max - pd.Timedelta(hours=12))) & (gdf['acq_datetime'] < (dt_max - pd.Timedelta(hours=4)))]

# greater than 12 hours; gdf4 > 12 hours
gdf4 = gdf[gdf['acq_datetime'] < (dt_max - pd.Timedelta(hours=12))]

# now let's make sure the sizes are correct. They should all add up to 14045
print ('Sizes %i, %i, %i, %i from total of %i' % (gdf1.count()[0],gdf2.count()[0],gdf3.count()[0],gdf4.count()[0], gdf.count()[0]))

# set our extent to Canada
extent = [-150, 40, -49, 79]
ax = world.plot(figsize=(10, 10), color="grey", edgecolor="black")

# set map extent
ax.set_xlim([extent[0],  extent[2]])
ax.set_ylim([extent[1],  extent[3]])

# add graph title
ax.set(title='Time Since Detection\nCanada wildfires July 12, 2023')

# Color code each set; also we are drawing in opposite order, so the older detections are drawn first so the newer ones are on the top
gdf4.plot(ax=ax, color="yellow", markersize=1)
gdf3.plot(ax=ax, color="orange", markersize=1)
gdf2.plot(ax=ax, color="red", markersize=1)
gdf1.plot(ax=ax, color="darkred", markersize=1)

plt.show()

!pip install contextily
import contextily as cx

extent = [-150, 40, -49, 79]
ax = world.plot(figsize=(10, 10), alpha=0)

# set our map extent
ax.set_xlim([extent[0],  extent[2]])
ax.set_ylim([extent[1],  extent[3]])

# set title
ax.set(title='Time Since Detection\nCanada wildfires July 12, 2023')
# turn off axis labels
ax.set_axis_off()

# Color code each set; also we are drawing in opposite order, so the older detections are drawn first so the newer ones are on the top
if gdf4.count()[0] > 0 :
  gdf4.plot(ax=ax, color="yellow", markersize=1)
if gdf3.count()[0] > 0 :
  gdf3.plot(ax=ax, color="orange", markersize=1)
if gdf2.count()[0] > 0 :
  gdf2.plot(ax=ax, color="red", markersize=1)
if gdf1.count()[0] > 0 :
  gdf1.plot(ax=ax, color="darkred", markersize=1)

# add basemap
cx.add_basemap(ax, crs=gdf1.crs)

# show our map plot
plt.show()

# To summarize our code
!pip install geodatasets cartopy contextily
import contextily as cx
import geopandas
import pandas as pd
import matplotlib.pyplot as plt
from cartopy import crs as ccrs
from geodatasets import get_path

# set our fire data
df = pd.read_csv('https://firms.modaps.eosdis.nasa.gov/content/notebooks/sample_viirs_snpp_071223.csv')
df_canada = df[(df['longitude'] >= -150) & (df['latitude'] >= 40) & (df['longitude'] <= -49) & (df['latitude'] <= 79)].copy()
df_canada['acq_datetime'] = pd.to_datetime(df_canada['acq_date'] + ' ' + df_canada['acq_time'].astype(str).str.zfill(4), format='%Y-%m-%d %H%M')
gdf = geopandas.GeoDataFrame(
    df_canada, geometry=geopandas.points_from_xy(df_canada.longitude, df_canada.latitude), crs="EPSG:4326"
)
dt_max = gdf['acq_datetime'].max()
gdf1 = gdf[gdf['acq_datetime'] >= (dt_max - pd.Timedelta(hours=1))]
gdf2 = gdf[(gdf['acq_datetime'] >= (dt_max - pd.Timedelta(hours=4))) & (gdf['acq_datetime'] < (dt_max - pd.Timedelta(hours=1)))]
gdf3 = gdf[(gdf['acq_datetime'] >= (dt_max - pd.Timedelta(hours=12))) & (gdf['acq_datetime'] < (dt_max - pd.Timedelta(hours=4)))]
gdf4 = gdf[gdf['acq_datetime'] < (dt_max - pd.Timedelta(hours=12))]

# set out plot
extent = [-150, 40, -49, 79]
world = geopandas.read_file(get_path("naturalearth.land"))
ax = world.plot(figsize=(10, 10), alpha=0)

ax.set_xlim([extent[0],  extent[2]])
ax.set_ylim([extent[1],  extent[3]])

ax.set(title='Time Since Detection\nCanada wildfires July 12, 2023')
ax.set_axis_off()

if gdf4.count()[0] > 0 :
  gdf4.plot(ax=ax, color="yellow", markersize=1)
if gdf3.count()[0] > 0 :
  gdf3.plot(ax=ax, color="orange", markersize=1)
if gdf2.count()[0] > 0 :
  gdf2.plot(ax=ax, color="red", markersize=1)
if gdf1.count()[0] > 0 :
  gdf1.plot(ax=ax, color="darkred", markersize=1)

cx.add_basemap(ax, crs=gdf1.crs)

plt.show()
import contextily as cx
import geopandas
import pandas as pd
import matplotlib.pyplot as plt
from cartopy import crs as ccrs
from geodatasets import get_path

# set our fire data (using the sample data, as real-time data for the current month requires API access or complex downloads)
df = pd.read_csv('https://firms.modaps.eosdis.nasa.gov/content/notebooks/sample_viirs_snpp_071223.csv')

# Create a copy for global data processing
df_global = df.copy()
df_global['acq_datetime'] = pd.to_datetime(df_global['acq_date'] + ' ' + df_global['acq_time'].astype(str).str.zfill(4), format='%Y-%m-%d %H%M').dt.tz_localize('UTC')
gdf_global = geopandas.GeoDataFrame(
    df_global, geometry=geopandas.points_from_xy(df_global.longitude, df_global.latitude), crs="EPSG:4326"
)

# ***MODIFICATION FOR REAL-TIME***
# Use the current UTC timestamp for 'real-time' calculation
dt_max = pd.Timestamp.now(tz='UTC')

# create our subsets for 4 color classes based on current time for GLOBAL data
gdf1_global = gdf_global[gdf_global['acq_datetime'] >= (dt_max - pd.Timedelta(hours=1))]
gdf2_global = gdf_global[(gdf_global['acq_datetime'] >= (dt_max - pd.Timedelta(hours=4))) & (gdf_global['acq_datetime'] < (dt_max - pd.Timedelta(hours=1)))]
gdf3_global = gdf_global[(gdf_global['acq_datetime'] >= (dt_max - pd.Timedelta(hours=12))) & (gdf_global['acq_datetime'] < (dt_max - pd.Timedelta(hours=4)))]
gdf4_global = gdf_global[gdf_global['acq_datetime'] < (dt_max - pd.Timedelta(hours=12))]

# Filter for India region (approximate coordinates) to highlight
df_india_highlight = df[(df['longitude'] >= 68) & (df['latitude'] >= 8) & (df['longitude'] <= 98) & (df['latitude'] <= 37)].copy()
df_india_highlight['acq_datetime'] = pd.to_datetime(df_india_highlight['acq_date'] + ' ' + df_india_highlight['acq_time'].astype(str).str.zfill(4), format='%Y-%m-%d %H%M').dt.tz_localize('UTC')
gdf_india_highlight = geopandas.GeoDataFrame(
    df_india_highlight, geometry=geopandas.points_from_xy(df_india_highlight.longitude, df_india_highlight.latitude), crs="EPSG:4326"
)

# create subsets for 4 color classes based on current time for INDIA HIGHLIGHT
gdf1_india = gdf_india_highlight[gdf_india_highlight['acq_datetime'] >= (dt_max - pd.Timedelta(hours=1))]
gdf2_india = gdf_india_highlight[(gdf_india_highlight['acq_datetime'] >= (dt_max - pd.Timedelta(hours=4))) & (gdf_india_highlight['acq_datetime'] < (dt_max - pd.Timedelta(hours=1)))]
gdf3_india = gdf_india_highlight[(gdf_india_highlight['acq_datetime'] >= (dt_max - pd.Timedelta(hours=12))) & (gdf_india_highlight['acq_datetime'] < (dt_max - pd.Timedelta(hours=4)))]
gdf4_india = gdf_india_highlight[gdf_india_highlight['acq_datetime'] < (dt_max - pd.Timedelta(hours=12))]

# Set global plot extent
extent = [-180, -90, 180, 90] # min_lon, min_lat, max_lon, max_lat for global view
world = geopandas.read_file(get_path("naturalearth.land"))
ax = world.plot(figsize=(15, 10), alpha=0.5, edgecolor='black') # Use a slightly larger figure for global, show land as grey outline

ax.set_xlim([extent[0],  extent[2]])
ax.set_ylim([extent[1],  extent[3]])

ax.set(title=f'Time Since Detection (as of {dt_max.strftime("%Y-%m-%d %H:%M UTC")})\nGlobal and India wildfires from sample data')
ax.set_axis_off()

# Plot global fires first with smaller markers
if gdf4_global.count()[0] > 0 :
  gdf4_global.plot(ax=ax, color="yellow", markersize=0.5, label="Global > 12 hours ago")
if gdf3_global.count()[0] > 0 :
  gdf3_global.plot(ax=ax, color="orange", markersize=0.5, label="Global 4-12 hours ago")
if gdf2_global.count()[0] > 0 :
  gdf2_global.plot(ax=ax, color="red", markersize=0.5, label="Global 1-4 hours ago")
if gdf1_global.count()[0] > 0 :
  gdf1_global.plot(ax=ax, color="darkred", markersize=0.5, label="Global <= 1 hour ago")

# Then overlay India fires with larger markers to highlight them
if gdf4_india.count()[0] > 0 :
  gdf4_india.plot(ax=ax, color="yellow", markersize=3, marker='o', alpha=0.8, label="India > 12 hours ago")
if gdf3_india.count()[0] > 0 :
  gdf3_india.plot(ax=ax, color="orange", markersize=3, marker='o', alpha=0.8, label="India 4-12 hours ago")
if gdf2_india.count()[0] > 0 :
  gdf2_india.plot(ax=ax, color="red", markersize=3, marker='o', alpha=0.8, label="India 1-4 hours ago")
if gdf1_india.count()[0] > 0 :
  gdf1_india.plot(ax=ax, color="darkred", markersize=3, marker='o', alpha=0.8, label="India <= 1 hour ago")

cx.add_basemap(ax, crs=gdf_global.crs, source=cx.providers.CartoDB.Positron)
ax.legend(title="Time Since Detection", loc='upper left', bbox_to_anchor=(1, 1))

plt.show()

